# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUpdateVaccineNametest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_updateVaccineNametest(self):
    self.driver.get("http://localhost/vaccine/Employee/view/updatename.php")
    self.driver.set_window_size(1090, 672)
    self.driver.find_element(By.NAME, "nmbr").click()
    self.driver.find_element(By.NAME, "nmbr").send_keys("12345")
    self.driver.find_element(By.NAME, "new_vaccine").click()
    self.driver.find_element(By.NAME, "new_vaccine").send_keys("faizer")
    self.driver.find_element(By.NAME, "submit").click()
  
