# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSearchVaccinatedListtest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_searchVaccinatedListtest(self):
    self.driver.get("http://localhost/vaccine/Employee/view/searchvaccinatedreg.php")
    self.driver.set_window_size(1054, 672)
    self.driver.find_element(By.NAME, "searchBox").click()
    self.driver.find_element(By.NAME, "searchBox").send_keys("1000000000")
    self.driver.find_element(By.NAME, "search").click()
    self.driver.find_element(By.NAME, "searchBox").click()
    self.driver.find_element(By.NAME, "searchBox").send_keys("12345")
    self.driver.find_element(By.NAME, "search").click()
  
