# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddVaccinatedtest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addVaccinatedtest(self):
    self.driver.get("http://localhost/vaccine/Employee/view/vaccinated.php")
    self.driver.set_window_size(986, 672)
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Jhuma")
    self.driver.find_element(By.ID, "genderFemale").click()
    self.driver.find_element(By.ID, "nmbr").click()
    self.driver.find_element(By.ID, "nmbr").send_keys("44556")
    self.driver.find_element(By.ID, "registration").click()
    self.driver.find_element(By.ID, "registration").send_keys("2024-11-07")
    self.driver.find_element(By.ID, "address").click()
    self.driver.find_element(By.ID, "address").send_keys("Dhaka")
    self.driver.find_element(By.ID, "hospital").click()
    self.driver.find_element(By.ID, "hospital").send_keys("Square")
    self.driver.find_element(By.ID, "vaccine").click()
    self.driver.find_element(By.ID, "vaccine").send_keys("Faizer")
    self.driver.find_element(By.ID, "vaccinated").click()
    self.driver.find_element(By.ID, "vaccinated").send_keys("2024-11-20")
    self.driver.find_element(By.NAME, "SUBMIT").click()
  
