# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegistrationtest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_registrationtest(self):
    self.driver.get("http://localhost/vaccine/Employee/view/registration.php")
    self.driver.set_window_size(1050, 672)
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("Arafat")
    self.driver.find_element(By.ID, "nid").click()
    self.driver.find_element(By.ID, "nid").send_keys("1234577889")
    self.driver.find_element(By.ID, "nationality").click()
    self.driver.find_element(By.ID, "nationality").send_keys("Bangladeshi")
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("arafat1971@gmail.com")
    self.driver.find_element(By.ID, "pass").click()
    self.driver.find_element(By.ID, "pass").send_keys("12345678")
    self.driver.find_element(By.ID, "birth").click()
    self.driver.find_element(By.ID, "birth").send_keys("2024-11-20")
    self.driver.find_element(By.ID, "birth").click()
    self.driver.find_element(By.ID, "birth").send_keys("2001-02-13")
    self.driver.find_element(By.ID, "nmbr").click()
    self.driver.find_element(By.ID, "nmbr").send_keys("01778135451")
    self.driver.find_element(By.ID, "genderMale").click()
    self.driver.find_element(By.ID, "address").click()
    self.driver.find_element(By.ID, "address").send_keys("Dhaka")
    self.driver.find_element(By.NAME, "ADD").click()
  
