# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDemoTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_demotest(self):
    self.driver.get("http://localhost/vaccin/Employee/view/login.php")
    self.driver.set_window_size(652, 672)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("gobindagoswamee@gmail.com")
    self.driver.find_element(By.ID, "pass").click()
    self.driver.find_element(By.ID, "pass").send_keys("1234")
    self.driver.find_element(By.NAME, "login").click()
    self.driver.close()
  
